### ISSUE TITLE
Even simpler inital steps

### ISSUE THREAD

**Issue by markmcgookin** [UnfinishedStuff/Pimoroni_Pico_Display_Pack_documentation#2]
I am an experienced software developer, but totally new to python, I only ever dabble with it.

I have the pico display, and have their source code and can run basic commands using the base python libraries using Thonny connected to my pico.

But I get the old 

`ImportError: no module named 'picodisplay'`

When I try to run the example... so obviously I haven't included the picodisplay module that the source is importing. But I have NO idea how to actually include it, deploy it to the pico, if I can just download the c++ files, or if I need to install them via thonny (I couldn't see them when searching in manage-packages)

Could you document how to take the module source files from github and actually use them. You sort of just dove into import statements, and never mentioned what to do with the files to make them usable on the device.

EDIT: So after some more reading I see that you have to recompile micropython yourself including the new modules and then install that as firmware on the pico. But some step by step instructions on that would be great.

**Comment by UnfinishedStuff** [comment]
You shouldn't need to do any recompiling, there's a different way to do it which I have mixed feelings on.  

Check the section called "Setting up the board and development tools".  You need to follow [Pimoroni's instructions](https://github.com/pimoroni/pimoroni-pico/blob/main/setting-up-micropython.md) for installing their MicroPython firmware which has their modules built-in.  Once you have the Pico showing up as a removable drive, you just copy Pimoroni's .uf2 file for the v0.0.5 Alpha release over, and a few moments later it'll be running MicroPython and have the Display Pack module included.

I'm honestly not such a fan of this because with MicroPython the files are hidden from the user.  With the slightly-different CircuitPython by Adafruit, when the drive shows up you can see module files/directories and copy and paste them back and forward as normal.

Maybe I should edit the section title to make that more clear.

**Comment by UnfinishedStuff** [comment]
Actually, looking at it again you're right.  I'm doing revisions at the moment, I'll add a clearer setup section to the list.

**Comment by UnfinishedStuff** [comment]
I've updated the docs with PR #4, laying out a more step-by-step guide for installing Pimoroni's firmware and adding a note below the Quickstart Guide that you need to do this before coding.  Let me know if it isn't clear or I've missed something.

**Comment by markmcgookin** [comment]
Man, I totally missed that step out. Thanks for the update!
