### ISSUE TITLE
ImportError: no module named 'picodisplay' with v1.19.6 firmware

### ISSUE THREAD

**Issue by RC-Projects** [UnfinishedStuff/Pimoroni_Pico_Display_Pack_documentation#8]
When attempting a simple `import picodisplay as display`, I am receiving a `ImportError: no module named 'picodisplay'` error. 

I used the latest pimoroni-pico-v1.19.6-micropython.uf2 firmware. The example python scripts work fine, but I can't seem to get the picodisplay to work. 

Any ideas?

**Comment by UnfinishedStuff** [comment]
Sorry for the slow response to this, work has been a bear.

Pimoroni have made some significant changes to how thier Pico software works, and I think the've deprecated PicoDisplay.  Because of this, a lot of the information in this repo is now out of date and won't work at all.  Whether or not I get time to update it I don't know, we'll see.

EDIT: Pimoroni have most of the documentation for PicoGraphics here: https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/modules/picographics

It's fairly detailed.

**Comment by RC-Projects** [comment]
Thanks, I was able to get picographics to work!
